# Generated by Django 4.2.7 on 2023-11-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter your name', max_length=100, verbose_name='Name')),
                ('email', models.EmailField(help_text='Enter your email', max_length=100, verbose_name='Email')),
                ('phone', models.CharField(help_text='Enter your phone number', max_length=12, verbose_name='Phone')),
                ('description', models.TextField(help_text='Information about contact', verbose_name='Description')),
            ],
        ),
    ]
